version: "3.9"
services:
  pizzeria:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - "8075:8075"
    depends_on:
      - postgres_db
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres_db:5432/Pizzeria

  postgres_db:
    image: postgres
    restart: always
    networks:
      - backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=Pizzeria
    ports:
      - "5432:5432"


networks:
  backend:
    driver: bridge