INSERT INTO status (id, name)
SELECT 1, 'ACCEPTED'
WHERE NOT EXISTS (SELECT 1 FROM status WHERE name = 'ACCEPTED')
UNION ALL
SELECT 2, 'IN_PROGRESS'
WHERE NOT EXISTS (SELECT 1 FROM status WHERE name = 'IN_PROGRESS')
UNION ALL
SELECT 3, 'DELAYED'
WHERE NOT EXISTS (SELECT 1 FROM status WHERE name = 'DELAYED')
UNION ALL
SELECT 4, 'READY_FOR_PICKUP'
WHERE NOT EXISTS (SELECT 1 FROM status WHERE name = 'READY_FOR_PICKUP')
UNION ALL
SELECT 5, 'IN_TRANSIT'
WHERE NOT EXISTS (SELECT 1 FROM status WHERE name = 'IN_TRANSIT')
UNION ALL
SELECT 6, 'COMPLETED'
WHERE NOT EXISTS (SELECT 1 FROM status WHERE name = 'COMPLETED')
UNION ALL
SELECT 7, 'CANCELLED'
WHERE NOT EXISTS (SELECT 1 FROM status WHERE name = 'CANCELLED');

INSERT INTO roles (id, name)
SELECT 1, 'ROLE_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_ADMIN')
UNION ALL
SELECT 2, 'ROLE_USER'
WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'ROLE_USER');